"""QT Database (QTDB) fiducial evaluation.

Evaluates the P/Q/R/S/T landmarks produced by ``ecg_monitor`` against the
reference waveform annotations of the PhysioNet QT Database.

Reference annotators
--------------------
QTDB ships two families of waveform annotations:

* ``q1c`` / ``q2c`` : manually reviewed reference beats (gold standard, but only
  ~30 beats per record and only for a subset of records).
* ``pu0`` / ``pu1`` : full-record annotations generated by ``ecgpuwave`` on
  signal 0 / signal 1.

By default this script tries ``q1c`` first (manual gold standard) and falls back
to ``pu0`` (full-record) when the manual file is missing. The annotator actually
used is recorded per record so results are interpretable.

Marker mapping (documented, not faked)
--------------------------------------
QTDB annotates P, QRS and T *peaks* plus QRS *onset*/*offset*. It does not
annotate the Q and S peaks directly. Therefore:

* P, R (QRS peak) and T are matched directly against annotated peaks.
* Q and S are compared only against the QRS onset / offset as an explicitly
  labelled approximate-boundary metric.

Example
-------
    python3 scripts/evaluate_qtdb.py --record sel100 --seconds 60
    python3 scripts/evaluate_qtdb.py --records sel100 sel102 --tolerance-ms 150
    python3 scripts/evaluate_qtdb.py --max-records 5
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import numpy as np

from ecg_monitor import delineate_pqrst, detect_r_peaks
from ecg_monitor.fiducials import (
    ReferenceFiducials,
    match_markers,
    parse_waveform_annotations,
    timing_error_stats,
)

# A small default record list drawn from QTDB (records exist on PhysioNet).
DEFAULT_RECORDS = [
    "sel100",
    "sel102",
    "sel103",
    "sel104",
    "sel114",
    "sel116",
    "sel117",
]

PEAK_TYPES = ("p", "r", "t")
BOUNDARY_TYPES = ("q_vs_qrs_onset_approx", "s_vs_qrs_offset_approx")


class DatasetUnavailable(RuntimeError):
    pass


def _load_qtdb_record(record: str, lead: int, annotators: list[str], local_dir: str | None = None):
    """Load a QTDB record and the first available annotator.

    Returns (signal, fs, ReferenceFiducials, annotator_used).
    Raises DatasetUnavailable on missing wfdb / network / record.
    """
    try:
        import wfdb
    except ImportError as exc:  # pragma: no cover - exercised via message only
        raise DatasetUnavailable(
            "wfdb is required for QTDB evaluation. Install with: "
            "pip install -r requirements.txt"
        ) from exc

    try:
        record_path = str(Path(local_dir) / record) if local_dir else record
        if local_dir:
            signals, fields = wfdb.rdsamp(record_path)
        else:
            signals, fields = wfdb.rdsamp(record, pn_dir="qtdb")
    except Exception as exc:  # network / missing record / etc.
        raise DatasetUnavailable(
            f"Could not read QTDB record {record!r}. Underlying error: {exc}"
        ) from exc

    fs = float(fields["fs"])
    if lead >= signals.shape[1]:
        lead = 0
    signal = signals[:, lead]

    reference = None
    annotator_used = None
    last_error = None
    for ext in annotators:
        try:
            if local_dir:
                ann_obj = wfdb.rdann(record_path, ext)
            else:
                ann_obj = wfdb.rdann(record, ext, pn_dir="qtdb")
        except Exception as exc:  # this annotator absent for this record
            last_error = exc
            continue
        parsed = parse_waveform_annotations(ann_obj.sample, ann_obj.symbol)
        if parsed.qrs_peaks.size > 0:  # only accept an annotator that yields beats
            reference = parsed
            annotator_used = ext
            break
        last_error = f"annotator {ext!r} contained no usable QRS peaks"
    if reference is None:
        raise DatasetUnavailable(
            f"No usable annotator {annotators} for QTDB record {record!r}. "
            f"Last error: {last_error}"
        )

    return signal, fs, reference, annotator_used


def _local_records(local_dir: str) -> list[str]:
    return sorted(path.stem for path in Path(local_dir).glob("*.hea"))


def _predicted_markers(signal: np.ndarray, fs: float):
    """Run the detector + delineator and collect predicted landmarks."""
    r_peaks = detect_r_peaks(signal, fs)
    markers = delineate_pqrst(signal, fs, r_peaks, sqi_level="usable_for_pqrst")
    pred = {
        "p": [m.p for m in markers if m.p is not None],
        "r": [int(m.r) for m in markers],
        "t": [m.t for m in markers if m.t is not None],
        "q": [m.q for m in markers if m.q is not None],
        "s": [m.s for m in markers if m.s is not None],
    }
    return pred


def _select_window(reference: ReferenceFiducials, n_samples: int, size: int, fs: float) -> tuple[int, int]:
    """Choose the [start, stop) window to evaluate.

    QTDB manual annotators (q1c/q2c) mark a short ~30-beat segment located deep
    inside the record, so a naive "first N seconds" window would miss them.
    When the reference annotations are clustered (span <= window), we cover that
    cluster; otherwise (full-record pu0/pu1) we take the first N seconds.
    """
    all_ref = np.concatenate([
        reference.p_peaks, reference.qrs_peaks, reference.t_peaks,
        reference.qrs_onsets, reference.qrs_offsets,
    ]) if reference.qrs_peaks.size or reference.p_peaks.size or reference.t_peaks.size else np.asarray([], dtype=int)
    if all_ref.size == 0:
        return 0, min(n_samples, size)
    margin = int(0.5 * fs)
    amin, amax = int(all_ref.min()), int(all_ref.max())
    start = max(0, amin - margin)
    stop = min(size, amax + margin)
    # Bound the window length to keep the (pure-Python) filters fast; the manual
    # QTDB annotations can form clusters far apart, so we anchor on the first one.
    max_len = max(n_samples, int(90.0 * fs))
    if stop - start > max_len:
        stop = min(size, start + max_len)
    return start, stop


def evaluate_record(record: str, seconds: float, lead: int, tolerance_ms: float, annotators: list[str], local_dir: str | None = None) -> dict:
    signal, fs, reference, annotator_used = _load_qtdb_record(record, lead, annotators, local_dir)
    n_samples = int(seconds * fs) if seconds and seconds > 0 else signal.size
    start, stop = _select_window(reference, n_samples, signal.size, fs)
    window = signal[start:stop]
    n = window.size

    def _clip(arr):
        arr = np.asarray(arr, dtype=int)
        arr = arr[(arr >= start) & (arr < stop)] - start
        return arr

    ref = ReferenceFiducials(
        p_peaks=_clip(reference.p_peaks),
        qrs_peaks=_clip(reference.qrs_peaks),
        t_peaks=_clip(reference.t_peaks),
        qrs_onsets=_clip(reference.qrs_onsets),
        qrs_offsets=_clip(reference.qrs_offsets),
        n_annotations=reference.n_annotations,
        n_unmapped=reference.n_unmapped,
    )

    pred = _predicted_markers(window, fs)
    tolerance_samples = tolerance_ms * fs / 1000.0

    ref_map = {"p": ref.p_peaks, "r": ref.qrs_peaks, "t": ref.t_peaks}
    pred_map = {"p": pred["p"], "r": pred["r"], "t": pred["t"]}

    row: dict = {
        "record": record,
        "annotator": annotator_used,
        "fs": fs,
        "window_start_s": float(start / fs),
        "window_seconds": float(n / fs),
        "lead": lead,
        "tolerance_ms": tolerance_ms,
        "n_ref_p": int(ref.p_peaks.size),
        "n_ref_r": int(ref.qrs_peaks.size),
        "n_ref_t": int(ref.t_peaks.size),
        "n_ref_qrs_onset": int(ref.qrs_onsets.size),
        "n_ref_qrs_offset": int(ref.qrs_offsets.size),
        "n_pred_p": len(pred["p"]),
        "n_pred_r": len(pred["r"]),
        "n_pred_t": len(pred["t"]),
        "unmapped_rate": ref.unmapped_rate,
    }

    n_beats = max(1, int(ref.qrs_peaks.size))
    all_abs_errors: list[float] = []
    per_fiducial: dict = {}

    for kind in PEAK_TYPES:
        result = match_markers(pred_map[kind], ref_map[kind], tolerance_samples)
        stats = timing_error_stats(result.signed_errors_samples, fs)
        n_ref_kind = ref_map[kind].size
        row[f"{kind}_matched"] = result.matched
        row[f"{kind}_false_positive"] = result.false_positive
        row[f"{kind}_missing"] = result.missing
        row[f"{kind}_coverage"] = result.coverage
        row[f"{kind}_mae_ms"] = stats["mae_ms"]
        row[f"{kind}_median_ae_ms"] = stats["median_ae_ms"]
        row[f"{kind}_std_ms"] = stats["std_ms"]
        row[f"{kind}_mae_samples"] = stats["mae_samples"]
        # A marker is "unavailable" for a beat when the reference lacks it.
        row[f"{kind}_unavailable_rate"] = float(max(0.0, 1.0 - n_ref_kind / n_beats)) if kind != "r" else 0.0
        per_fiducial[kind] = {"matched": result.matched, "stats": stats}
        all_abs_errors.extend(result.abs_errors_samples().tolist())

    # Approximate Q/S boundary comparison (clearly labelled, not true Q/S peaks).
    boundary_pairs = {
        "q_vs_qrs_onset_approx": (pred["q"], ref.qrs_onsets),
        "s_vs_qrs_offset_approx": (pred["s"], ref.qrs_offsets),
    }
    for kind, (pred_vals, ref_vals) in boundary_pairs.items():
        result = match_markers(pred_vals, ref_vals, tolerance_samples)
        stats = timing_error_stats(result.signed_errors_samples, fs)
        row[f"{kind}_matched"] = result.matched
        row[f"{kind}_coverage"] = result.coverage
        row[f"{kind}_mae_ms"] = stats["mae_ms"]
        row[f"{kind}_median_ae_ms"] = stats["median_ae_ms"]
        per_fiducial[kind] = {"matched": result.matched, "stats": stats}

    overall = timing_error_stats(np.asarray(all_abs_errors, dtype=float), fs)
    row["overall_mae_ms"] = overall["mae_ms"]
    row["overall_median_ae_ms"] = overall["median_ae_ms"]
    row["overall_std_ms"] = overall["std_ms"]
    row["_per_fiducial"] = per_fiducial
    return row


def _aggregate(rows: list[dict]) -> dict:
    agg = {"n_records": len(rows), "by_marker": {}}
    for kind in PEAK_TYPES + BOUNDARY_TYPES:
        maes = [r[f"{kind}_mae_ms"] for r in rows if r.get(f"{kind}_mae_ms") is not None]
        covs = [r[f"{kind}_coverage"] for r in rows if r.get(f"{kind}_coverage") is not None]
        agg["by_marker"][kind] = {
            "mean_mae_ms": float(np.mean(maes)) if maes else None,
            "median_mae_ms": float(np.median(maes)) if maes else None,
            "mean_coverage": float(np.mean(covs)) if covs else None,
            "n_records_with_marker": len(maes),
        }
    return agg


def _print_summary(rows: list[dict], agg: dict) -> None:
    for r in rows:
        print(f"\n== record={r['record']} annotator={r['annotator']} fs={r['fs']:g}Hz "
              f"window={r['window_start_s']:.1f}s+{r['window_seconds']:.1f}s ==")
        print(f"reference: P={r['n_ref_p']} QRS={r['n_ref_r']} T={r['n_ref_t']} "
              f"(qrs_onset={r['n_ref_qrs_onset']} qrs_offset={r['n_ref_qrs_offset']}, "
              f"unmapped_rate={r['unmapped_rate']:.3f})")
        for kind in PEAK_TYPES:
            mae = r[f"{kind}_mae_ms"]
            mae_s = f"{mae:.2f}ms" if mae is not None else "NA"
            print(f"  {kind.upper():<2} matched={r[f'{kind}_matched']:<4} "
                  f"coverage={r[f'{kind}_coverage']:.3f} "
                  f"MAE={mae_s} unavailable_rate={r[f'{kind}_unavailable_rate']:.3f}")
        for kind in BOUNDARY_TYPES:
            mae = r[f"{kind}_mae_ms"]
            mae_s = f"{mae:.2f}ms" if mae is not None else "NA"
            print(f"  {kind} matched={r[f'{kind}_matched']} coverage={r[f'{kind}_coverage']:.3f} MAE={mae_s}")
    print("\n== aggregate ==")
    print(f"records evaluated: {agg['n_records']}")
    for kind, m in agg["by_marker"].items():
        mm = f"{m['mean_mae_ms']:.2f}ms" if m["mean_mae_ms"] is not None else "NA"
        mc = f"{m['mean_coverage']:.3f}" if m["mean_coverage"] is not None else "NA"
        print(f"  {kind:<24} mean_MAE={mm} mean_coverage={mc} n_records={m['n_records_with_marker']}")


def _save(rows: list[dict], agg: dict, out_csv: Path, out_json: Path) -> None:
    csv_rows = [{k: v for k, v in r.items() if not k.startswith("_")} for r in rows]
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    if csv_rows:
        fieldnames = list(csv_rows[0].keys())
        with out_csv.open("w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(csv_rows)
    with out_json.open("w") as f:
        json.dump({"records": csv_rows, "aggregate": agg}, f, indent=2)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--record", default="sel100", help="Single QTDB record id, e.g. sel100")
    parser.add_argument("--records", nargs="*", help="Evaluate multiple QTDB records")
    parser.add_argument("--max-records", type=int, default=None, help="Cap number of records from the default list")
    parser.add_argument("--seconds", type=float, default=60.0, help="Seconds from record start (0 = whole record)")
    parser.add_argument("--lead", type=int, default=0, help="Signal lead index")
    parser.add_argument("--tolerance-ms", type=float, default=150.0, help="Matching tolerance in milliseconds")
    parser.add_argument("--local-dir", default=None, help="Read QTDB records from a local wfdb.dl_database directory")
    parser.add_argument("--all-local", action="store_true", help="Evaluate all .hea records under --local-dir")
    parser.add_argument(
        "--annotator",
        default="auto",
        help="Annotator: 'auto' (q1c then pu0), or an explicit extension like q1c/pu0/pu1",
    )
    parser.add_argument("--output", default="results/qtdb_fiducial_results.csv", help="CSV output path")
    parser.add_argument("--json-output", default="results/qtdb_fiducial_results.json", help="JSON output path")
    args = parser.parse_args(argv)

    if args.all_local:
        if not args.local_dir:
            raise SystemExit("--all-local requires --local-dir")
        records = _local_records(args.local_dir)
    elif args.records:
        records = args.records
    elif args.max_records is not None:
        records = DEFAULT_RECORDS[: args.max_records]
    else:
        records = [args.record]

    annotators = ["q1c", "pu0"] if args.annotator == "auto" else [args.annotator]

    rows: list[dict] = []
    failures: list[str] = []
    for record in records:
        try:
            rows.append(evaluate_record(record, args.seconds, args.lead, args.tolerance_ms, annotators, args.local_dir))
        except DatasetUnavailable as exc:
            failures.append(f"{record}: {exc}")
            print(f"[skip] {record}: {exc}", file=sys.stderr)

    if not rows:
        print(
            "\nNo QTDB records could be evaluated. This usually means wfdb is not "
            "installed or PhysioNet is unreachable.\n"
            "To run this evaluation after installing deps / restoring internet:\n"
            "  python3 scripts/evaluate_qtdb.py --record sel100 --seconds 60",
            file=sys.stderr,
        )
        return 2

    agg = _aggregate(rows)
    _print_summary(rows, agg)
    out_csv = Path(args.output)
    out_json = Path(args.json_output)
    _save(rows, agg, out_csv, out_json)
    print(f"\nsaved_csv={out_csv}")
    print(f"saved_json={out_json}")
    if failures:
        print(f"skipped_records={len(failures)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
